### ISSUE TITLE
Problem in running flutter App 

### ISSUE THREAD

**Issue by ankit007im** [flutter/udacity-course#139] opened 2018-11-02 21:16 UTC
* Error running Gradle:
Exit code 1 from: D:\projectFlutter\hello_rectangle\android\gradlew.bat app:properties:
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\projectFlutter\hello_rectangle\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not resolve all files for configuration 'classpath'.
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.1.2).
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/lint/lint-gradle-api/26.1.2/lint-gradle-api-26.1.2.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Please review your Gradle project setup in the android/ folder.
Exited (sigterm)

**Comment by maryx** [comment] 2018-11-06 21:55
This might be a duplicate of https://github.com/flutter/udacity-course/issues/137 and related to https://github.com/flutter/flutter/issues/23996.

**Comment by maryx** [comment] 2018-11-09 18:44
Also see flutter/flutter#23404; it might help.
@ankit007im let us know!
If resolved, feel free to close the issue.

**Closed** 2018-11-10 18:11 UTC
